pipeline {
    agent any    
    stages {
        stage('Build') {
            steps {
                sh 'mv ./maven-samples/* .'
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                sh 'scp -i /var/lib/jenkins/.ssh/id_rsa1 /var/lib/jenkins/workspace/Fully-automated-pipeline/multi-module/webapp/target/*.war root@35.190.145.164:/home/tomcat/apache-tomcat-8.5.31/webapps'
                sh 'ssh -i /var/lib/jenkins/.ssh/id_rsa1 root@35.190.145.164 chown tomcat:tomcat /home/tomcat/apache-tomcat-8.5.31/webapps/*.war'
            }
            post {
                success {
                    sh 'echo deployment successful'
                }
            }
        }
        
    }
}
