pipeline {
    agent any    
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                sh 'scp **/*.war 35.237.200.38:/home/tomcat/apache-tomcat-8.5.31/webapps'
                sh 'ssh 35.237.200.38 chown tomcat:tomcat /home/tomcat/apache-tomcat-8.5.31/webapps/*.war'
            }
            post {
                success {
                    sh 'echo "deployment successful" 
                }
            }
        }
        
    }
}
